username = ["admin", "fran004", "fran005", "fran006", "fran007", "fran008", "user2"]
password = ["hopcharge@901", "hopcharge@321", "JAhopcharge@321", "RYhopcharge@321", "ANhopcharge@321", "DMhopcharge@321", "hopcharge@901"]
